name: elites_live
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  flutter_screenutil: ^5.9.3
  get: ^4.7.2
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  contentsize_tabbarview: ^0.0.2
  dotted_border: ^3.1.0
  flutter_spinkit: ^5.2.1
  pinput: ^5.0.1
  dio: ^5.8.0+1
  logger: ^2.0.1
  shared_preferences: ^2.3.5
  mime: ^2.0.0
  file_picker: ^10.3.3
  image_picker: ^1.2.0
  permission_handler: ^12.0.1
  url_launcher: ^6.3.1
  flutter_easyloading: ^3.0.5
  intl: ^0.20.2
  percent_indicator: ^4.2.5
  fl_chart: ^1.0.0
  expandable_text: ^2.3.0
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  google_sign_in: ^6.3.0
  firebase_messaging: ^16.0.2
  photo_view: ^0.15.0
  shimmer: ^3.0.0
  in_app_purchase: ^3.2.3
  http: ^1.5.0
  http_parser: ^4.1.2
  path: ^1.9.1
  table_calendar: ^3.2.0
  video_player: ^2.10.0
  emoji_picker_flutter: ^4.3.0
  font_awesome_flutter: ^10.10.0
  avatar_stack: ^3.0.0
  flutter_launcher_icons: ^0.14.4
  zego_uikit_prebuilt_live_streaming: ^3.15.3
  zego_uikit: ^2.28.34
  web_socket_channel: ^3.0.3
  change_app_package_name: ^1.5.0
  webview_flutter: any
  webview_flutter_android: any
  webview_flutter_wkwebview: any
  flutter_local_notifications: ^19.5.0






dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/